FROM node

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/frontend

WORKDIR /usr/src/app/frontend

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

ENV NEXT_PUBLIC_SITE_KEY=6Lf7yHkhAAAAAPWsmY5MDoWIbHjLvX1aldXvT0hU

RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start" ]