version: '3'
services:

  frontend:
    build: ./frontend 
    ports: 
      - "3000:3000" 
    container_name: frontend-docker
    restart: always 
    links:
      - backend
  
  backend:
    build: ./backend
    ports:
      - "3333:3333"
    container_name: backend-docker
    restart: always
    links:
      - db

  db:
    image: postgres
    ports:
    - "5432:5432"
    container_name: database-docker
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=selecaoglobo