FROM node

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/backend

WORKDIR /usr/src/app/backend

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

ENV SECRET_KEY=6Lf7yHkhAAAAABNRJGroRxnL8WSSVTXdhYZmeJfp

EXPOSE 3333
# Command to run our app
CMD [ "yarn", "start"]
